# Welcome to Jekyll!
dev: NdanG
title: Plus62store
email: plus6store.info@gmail.com
avatar: https://1.bp.blogspot.com/-1bWHHqO2Jt0/X2ZgjgIVRVI/AAAAAAAAFZ8/XCb6roqGxhIn-K34II1L8BuLDoAePrmsgCLcBGAsYHQ/s0/192x192.png
description: Jual Masker Bordir Tasikmalaya..
baseurl: "" 
url: "https://plus62store.github.io"
twitter_username: x1666
github_username: daffadevhosting
fb-pixel: 904845437026791
fb-appID: 437300347340287
fb-admin: 158878762428839
fb-profile: 435671100899312
fb-pages: 107881477662203
signal-id: 6cc17e38-ff1c-4853-8a7e-a513caa8ac27
safari-web-ID: web.onesignal.auto.0f4ef0fc-d020-4184-9066-253532c318fc
G-verify: 
comen: 30234

# Google Auth
WA_KEY: 085156416662
SITE_KEY: 6Lf8BdkpAAAAAElS8xJWvKYvFtTvIBMD3GKQn0sz
API_KEY: AIzaSyCh346K5NgNSvVq6Mv817GH_E6cPDurR2s
AUTH_DOMAIN: plus62bordir.firebaseapp.com
DATABASE_URL: https://plus62bordir-default-rtdb.asia-southeast1.firebasedatabase.app
PROJECT_ID: plus62bordir
STORAGE_BUCKET: plus62bordir.appspot.com
SENDER_ID: 787412546935
APP_ID: 1:787412546935:web:919338bbff32eada8cdd72
MEASUREMENT_ID: G-C082YPREP9

# Build settings
plugins:
  - jekyll-feed
  - jekyll-dotenv
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-figure

collections:
  blog:
    output: true

permalink: /product/:title/

defaults:
- scope:
    type: posts
  values:
    layout: shop

- scope:
    type: checkout
  values:
    layout: checkout-page

- scope:
    type: cart
  values:
    layout: cart-page

- scope:
    type: pages
  values:
    layout: page

- scope:
    type: blog
  values:
    layout: post

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/category/:name/'
    tags: '/tag/:name/'

compress_html:
  clippings: all
  ignore:
    envs: development

exclude: [lib, config.rb, .sass-cache, .env, Capfile, config, log, Rakefile, Rakefile.rb, tmp, Gemfile, Gemfile.lock, README.md, LICENSE.md, node_modules, gulpfile.js, package-lock.json]
